frontend:
  image: registry.gitlab.rebirthmonkey.com/lab/app/frontend
  tag: TAG_TO_BE_REPLACED
  autoscaling:
    averageUtilization: 90
backend:
  image: registry.gitlab.rebirthmonkey.com/lab/app/backend
  tag: TAG_TO_BE_REPLACED
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
  